### ISSUE TITLE
why no pmc_est and pmc_greed????

### ISSUE THREAD

**Issue by simple1213** [justanothergithubber/corr-im#1]
![image](https://user-images.githubusercontent.com/65207188/179221686-b3354ba0-6de4-4e0e-98e9-cc4adb3407d5.png)

**Comment by justanothergithubber** [comment]
You will need to build from my fork at https://github.com/justanothergithubber/pruned-monte-carlo
Alternatively, you can use any Monte Carlo method, even one implemented in Python.
